server:
  port: 80

spring:
  application:
    name: cloud-order-server

#eureka的配置
eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka #单机版，单个地址
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka  #集群版