server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/springCloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

#eureka的配置
eureka:
  client:
    register-with-eureka: true #向注册中心注册自己
    fetchRegistry: true #检索服务
    service-url:
      #defaultZone: http://localhost:7001/eureka   #注册地址，单机单个地址
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka  #集群版

#显示实例的ip地址和修改默认的实例名，默认为(DESKTOP-44EPSQL:cloud-payment-service:8001,修改后为payment8001
#鼠标放在名称上，左下角会显示ip地址
  instance:
    instance-id: payment8001
    prefer-ip-address: true

#Eureka客户端向服务端发送心跳的时间间隔，单位为秒（默认是30秒）
    lease-renewal-interval-in-seconds: 10
#Eurekaf服务端在收到最后一次心跳后等待时间上限，单位为秒（默认是90秒），超时将剔除服务
    lease-expiration-duration-in-seconds: 2

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: cn.hzu.SpringCloud.entities

